---
- name: Set content to static motd
  copy:
    content: |
      {{ motd_content }}
    dest: "/etc/motd"
    mode: '0644'
  when: motd_content is defined and motd_file is not defined and not motd_remove | bool
  tags: ["motd"]

- name: Remove static motd
  file:
    path: "/etc/motd"
    state: absent
  when: motd_content is defined and motd_file is not defined and motd_remove | bool
  tags: ["motd"]

- name: Add content to dynamic motd
  template:
    src: "etc/update-motd.d/motd.txt.j2"
    dest: "/etc/update-motd.d/{{ motd_file }}"
    mode: a+x
  when: motd_content is defined and motd_file is defined and not motd_remove | bool
  tags: ["motd"]

- name: Remove content from dynamic motd
  file:
    path: "/etc/update-motd.d/{{ motd_file }}"
    state: absent
  when: motd_file is defined and motd_remove | bool
  tags: ["motd"]
